spring.application.name=job-portal-system

spring.profiles.active=dev

#database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME}

#hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
app.jwt.secret=${JWT_SECRET}
# Access Token: 15 phút
app.jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
# Refresh Token: 30 ngày
app.jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION}